extends:
  - neko
  - plugin:react/recommended
  - plugin:react-hooks/recommended
plugins:
  - react
  - react-hooks
rules:
  import/no-unresolved:
    - 2
    - ignore:
      - dayjs
      - demo_module_federation
      - \?raw$
      - ^@/
      - ^@app